project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on-Exercise3"
            href: "Hands-on-Exercise3/Hands-on_Ex03.html"
          - text: "Hands-on-Exercise4"
            href: "Hands-on-Exercise4/Hands-on_Ex04.html"
          - text: "Hands-on-Exercise5"
            href: "Hands-on-Exercise5/Hands-on_Ex05.html"
          - text: "Hands-on-Exercise7"
            href: "Hands-on-Exercise7/Hands-on7.html"
          - text: "Hands-on-Exercise8"
            href: "Hands-on-Exercise8/Hands-on-Exercise8.html"
          - text: "Hands-on-Exercise9"
            href: "Hands-on-Exercise9/Hands-on-Exercise9.html"

      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-on-Exercise1/Take-on-Exercise1.html"
          - text: "Take-home Exercise 2"
            href: "Take-on-Exercise2/Take-on-Exercise2.html"

    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    smooth-scroll: true
    code-fold: false
    code-overflow: wrap
    page-layout: article

editor: visual

execute:
  warning: false
  echo: true